### PR TITLE
fix: support `PQ_LIB_DIR` env variable

### LINKED ISSUE #1: Using on OS X: 'Symbol not found: __cg_jpeg_resync_to_restart'
I tried using diesel but something gives the following error on a mac from just adding the `pq-sys` dependency:

```
> cat Cargo.toml
[package]
name = "testing"
version = "0.1.0"
[dependencies]
pq-sys = "0.2.1"

> cat src/lib.rs
extern crate pq_sys;

> cargo test --verbose
       Fresh libc v0.2.13
       Fresh pq-sys v0.2.1
       Fresh testing v0.1.0 (file:///Users/user/testing)
     Running `/Users/user/testing/target/debug/testing-0688888a7aeac232`
dyld: Symbol not found: __cg_jpeg_resync_to_restart
  Referenced from: /System/Library/Frameworks/ImageIO.framework/Versions/A/ImageIO
  Expected in: /usr/local/lib/libJPEG.dylib
 in /System/Library/Frameworks/ImageIO.framework/Versions/A/ImageIO
error: Process didn't exit successfully: `/Users/user/testing/target/debug/testing-0688888a7aeac232` (signal: 5, SIGTRAP: trace/breakpoint trap)

Caused by:
  Process didn't exit successfully: `/Users/user/testing/target/debug/testing-0688888a7aeac232` (signal: 5, SIGTRAP: trace/breakpoint trap)
```

### PR DESCRIPTION
**Pull request by compressed**
Setting the environment variable seems to reduce any potential breakage for others relying on the existing behavior. For mac, anyone using homebrew will have to make a change anyway once they move to beta and later.

Fix #1

### CODE REVIEW

File: build.rs [hunk 1]
```diff
@@ -1,11 +1,18 @@
...
+    if lib_dir.is_none() {
+        for output in Command::new("pg_config").arg("--libdir").output() {
+            if output.status.success() {
+                for path in String::from_utf8(output.stdout) {
+                    println!("cargo:rustc-link-search=native={}", &path);
+                }
             }
         }
+    } else {
+        println!("cargo:rustc-link-search=native={}", lib_dir.unwrap());
```
Comment (sgrif) [inline build.rs]: Can you change this to:

```rust
if let Ok(lib_dir) = env::var("PQ_LIB_DIR") {
  println!("cargo:rustc-link-search=native={}", lib_dir);
} else {
  // ...
}
```

Comment (compressed) [inline build.rs]: Good call, rebased.

**Comment by compressed** [comment]
Thanks for merging! Can you publish a new version of this crate?

**Comment by sgrif** [comment]
Yes, I'm trying to wrap up a release of Diesel in the next day or two and will publish this with it.

**Comment by compressed** [comment]
Great, thanks!
